# Generated by Django 4.0.3 on 2024-09-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('subject', models.CharField(blank=True, max_length=250, null=True)),
                ('course', models.CharField(blank=True, max_length=250, null=True)),
                ('teaching_reference', models.FileField(blank=True, null=True, upload_to='teaching_materials/')),
                ('delete_flag', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Teaching Materials',
            },
        ),
    ]
