# Generated by Django 4.0.3 on 2024-09-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='delete_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='user',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='membership_type',
            field=models.CharField(choices=[('1', 'Student'), ('2', 'Adult'), ('3', 'Senior'), ('2', 'Teacher')], default=1, max_length=3),
        ),
    ]
