# Generated by Django 4.0.3 on 2024-09-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0002_borrow_delete_flag_alter_borrow_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='membership_type',
            field=models.CharField(choices=[('1', 'Student'), ('2', 'Adult'), ('3', 'Senior'), ('4', 'Teacher')], default=1, max_length=4),
        ),
    ]
